### ISSUE TITLE
Color text when opening menu

### ISSUE THREAD

**Issue by stephaniehutama** [emersonsm/w40#2]
Firstly i love your theme especially the rainbow. I used it before on my macbook but when i started to work with my work laptop i used other theme and now starting to use again on my work laptop.. 
But one think i just realized, i dont know if the bug is just on me but i would like to see the options in the menu, because in my opinion, this way it's pretty annoying that i only able to look at the options when i hover each one of them.
![image](https://github.com/emersonsm/w40/assets/128687355/07d5f9e0-2cda-4c3f-80ba-43bef2ee9b47)

I would really appreciate if you can agree with me and fix this. Thank you so much for the theme it enhanced my mood everyday :)

**Comment by stephaniehutama** [comment]
Sorry, it seems like this issue was not caused by this theme, my bad XD

**Comment by emersonsm** [comment]
> Firstly i love your theme especially the rainbow. I used it before on my macbook but when i started to work with my work laptop i used other theme and now starting to use again on my work laptop.. But one think i just realized, i dont know if the bug is just on me but i would like to see the options in the menu, because in my opinion, this way it's pretty annoying that i only able to look at the options when i hover each one of them. ![image](https://private-user-images.githubusercontent.com/128687355/340508892-07d5f9e0-2cda-4c3f-80ba-43bef2ee9b47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTI3NDUsIm5iZiI6MTcyNTExMjQ0NSwicGF0aCI6Ii8xMjg2ODczNTUvMzQwNTA4ODkyLTA3ZDVmOWUwLTJjZGEtNGMzZi04MGJhLTQzYmVmMmVlOWI0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMzU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzU2ZDFlZDE4MzRhMzBmMzA5MjU5ZDEwODJiMGNhYjYzNzFmZjllYWM0MjI5ZjMyOTM1NzJjZDZlN2QxNzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pm6amlf_Eu_iNAQv9pFZt6C6yZx-lNoyvAWZE9WYDWM)
> 
> I would really appreciate if you can agree with me and fix this. Thank you so much for the theme it enhanced my mood everyday :)


Hello Stephanie, thank you for using my theme and kind words, I will check this problem as soon as possible  with another improvements as well, probably until the end of september, sorry for long time to answer

**Comment by emersonsm** [comment]
@stephaniehutama Better late than never, I adjusted the theme. If you want to install the most up-to-date version, I renamed it; just follow the instructions of repo.
